# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('types', models.CharField(choices=[(1, 'steel'), (2, 'wood'), (3, 'glass')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mobility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('types', models.CharField(choices=[(1, 'wheels'), (2, 'thrusters'), (3, 'tracks')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other', models.IntegerField()),
                ('hull', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roboticsworkshop.Hull')),
                ('mobility', models.ManyToManyField(to='roboticsworkshop.Mobility')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('types', models.CharField(choices=[(1, 'lance'), (2, 'rocket_launcher'), (3, 'laser_gun')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='robot',
            name='weapon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roboticsworkshop.Weapon'),
        ),
    ]
